<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../SharpCAT2.Common/SharpCAT2.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- Explicitly exclude files that should only be in the Client project -->
    <Compile Remove="ClientCommandProcessor.cs" />
    <Compile Remove="ClientConstants.cs" />
    <Compile Remove="Program.cs" />
  </ItemGroup>

</Project>