<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../SharpCAT2.Core/SharpCAT2.Core.csproj" />
    <ProjectReference Include="../SharpCAT2.ServerLibrary/SharpCAT2.ServerLibrary.csproj" />
  </ItemGroup>



</Project>